### ISSUE TITLE
Malicious shard might create hash conflicts in receipts

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearcore#1838]
if a shard is completely compromised it can produce a receipt with a conflicting hash. E.g. the hash might conflict either with some other receipt or with a transaction. For a transaction it would trigger failed to decode during borsh. For a receipt we might return a wrong receipt or have receipt conflicts.
Eventually it will be challenged and reverted, but we need to make sure it doesn’t crash the node and we handle it correctly.

**Comment by evgenykuzyakov** [comment]
Here is the scenario:

1. A malicious chunk producer creates an invalid chunk with invalid transition.
1. This chunk is included in the block and no one challenged this chunk.
1. A new malicious chunk is produced on top the previous malicious chunk.
1. A malicious challenge is created for the 2nd malicious chunk. The challenge is legit by itself, but it's built on top of 1st malicious chunk. The 1st chunk may contain any state and any state root, because it was invalid. So the state proof in the challenge is valid.
1. When every regular node tries to validate a malicious challenge they might crash on any unexpected storage operation.

The 2nd chunk can also contain any invalid transactions or receipts. So the input to the Runtime can be almost arbitrary picked by the malicious nodes.

**Comment by nearmax** [comment]
Assigning to @SkidanovAlex since it might be triggering failure on chain side.

**Comment by bowenwang1996** [comment]
Is this fixed in #2155?

**Comment by nearmax** [comment]
> Is this fixed in #2155?

Assigning to @evgenykuzyakov  to provide reply.

**Comment by evgenykuzyakov** [comment]
It's addressed on Runtime side. I think Runtime is pretty safe, since it doesn't have `unwrap`s or `expect`s and doesn't trust the state at all.
It's likely still an issue on RPC side and maybe on chain side

**Comment by bowenwang1996** [comment]
I don't think it's an issue on the rpc side given that we prohibit querying receipts. On the chain side I don't see any issue because validators cannot inject receipts arbitrarily since receipts are all merklized and verified when they are received.

**Comment by evgenykuzyakov** [comment]
So if a shard produces an invalid `ExecutionOutcome` with the result `SuccessReceiptId` pointing at the transaction itself. It might create the infinite recursion during fetching of `get_recursive_transaction_results`

**Comment by bowenwang1996** [comment]
@evgenykuzyakov that's fine. The query will just time out.

**Comment by nearmax** [comment]
@bowenwang1996 AFAIU this attacks honest validator.

**Comment by bowenwang1996** [comment]
This can only happen if the shard is controlled by a malicious majority, which means that honest validators, if any, will submit a challenge, and I think it is fine if they are temporarily subject to this attack before the chain confirms the challenge and slash malicious actors. Also moving this to post mainnet milestone as we will not have multiple shards first.

**Comment by bowenwang1996** [comment]
looks like no action items here. Closing
