### ISSUE TITLE
We expected `peer_id` to belong to a component warnings

### ISSUE THREAD

**Issue by mzhangmzz** [near/nearcore#5563]
I started a new testnet rpc node recently and I saw the log is flooded with these warnings 

```
Dec 01 18:52:33.547  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.547  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere
Dec 01 18:52:33.548  WARN near_network::routing::routing_table_actor: We expected `peer_id` to belong to a component 13059, but it doesn't belong anywhere```

Not sure if they indicate any issues or just a benign warning. In the previous case, we should fix the issue. In the latter case, we should decrease the frequency of printing these warnings.

**Comment by mzhangmzz** [comment]
cc @mm-near @pmnoxx

**Comment by pmnoxx** [comment]
@mzhangmzz Hey, thanks. It turns out that we have been deleting the same value from disk storage multiple times.
This should fix the issue: https://github.com/near/nearcore/issues/5563

**Comment by mzhangmzz** [comment]
> @mzhangmzz Hey, thanks. It turns out that we have been deleting the same value from disk storage multiple times. This should fix the issue: #5563

Thanks for looking into this! You might have posted the wrong link for a PR though

**Comment by pmnoxx** [comment]
@mzhangmzz Hey, thanks. It turns out that we have been deleting the same value from disk storage multiple times.
This should fix the issue: https://github.com/near/nearcore/pull/5566

**Comment by pmnoxx** [comment]
There is also a small bug, where the structure will not be cleaned properly:
https://github.com/near/nearcore/pull/5567

**Comment by frol** [comment]
I still see these warnings in 1.23.1 release. Should have the fix been part of 1.23.x series or will it only land with 1.24?

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/304265/149661081-cdce73f8-d8b7-40a7-a12a-cb07564397ed.png">

**Comment by pmnoxx** [comment]
@frol This log has been removed from the code. It's best to ask the person doing releases when it's going to be pushed to the binary release.

**Comment by frol** [comment]
I see, thanks
